<?xml version="1.0"?>
<robot name="racecar" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find car_description)/urdf/macros.xacro" />
    <link name="base_link"/>

<!-- Add the chassis with its joints -->

    <link name="chassis">
        <visual>
            <xacro:chassis_geometry/>
        </visual>
        <collision>
            <xacro:chassis_geometry/>
        </collision>
        <inertial>
            <xacro:chassis_inertial_params />
        </inertial>
    </link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis" />
    </joint>

<!-- Add the rear wheels with their joints -->
    <link name="left_rear_wheel">
        <inertial>
            <xacro:wheels_inertial_params z_offset="0" />
        </inertial>
        <visual>
            <xacro:wheel_geometry prefix="left_rear" />
        </visual>
        <collision>
            <xacro:wheel_collision_geometry />
        </collision>
    </link>

    <joint name="left_rear_wheel_joint" type="continuous">
        <origin xyz="${wheelbase/2} ${wheel_separation/2} 0.02" rpy="${pi/2} 0 0" />
        <parent link="chassis" />
        <child link="left_rear_wheel" />
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="100" />
    </joint>

    <link name="right_rear_wheel">
        <inertial>
            <xacro:wheels_inertial_params z_offset="0" />
        </inertial>
        <visual>
            <xacro:wheel_geometry prefix="right_rear" />
        </visual>
        <collision>
            <xacro:wheel_collision_geometry />
        </collision>
    </link>

    <joint name="right_rear_wheel_joint" type="continuous">
        <origin xyz="${-wheelbase/2} ${wheel_separation/2} 0.02" rpy="${pi/2} 0 0" />
        <parent link="chassis" />
        <child link="right_rear_wheel" />
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="100" />
    </joint>

    <link name="left_steering_hinge">
        <inertial>
            <xacro:steering_hinge_inertial_params z_offset="0"/>
        </inertial>
        <visual>
            <xacro:steering_hinge_geometry prefix="left" />
        </visual>
         <collision>
              <xacro:steering_hinge_geometry prefix="left" />
        </collision>
    </link>

    <joint name="left_steering_hinge_joint" type="revolute">
        <origin xyz="${wheelbase/2} ${-wheel_separation/2} 0.02" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="left_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit lower="-0.785" upper="0.785" effort="10" velocity="10" />
    </joint>


    <link name="right_steering_hinge">
        <inertial>
            <xacro:steering_hinge_inertial_params z_offset="0"/>
        </inertial>
        <visual>
            <xacro:steering_hinge_geometry prefix="right" />
        </visual>
        <collision>
            <xacro:steering_hinge_geometry prefix="right" />
        </collision>
    </link>

    <joint name="right_steering_hinge_joint" type="revolute">
        <origin xyz="${-wheelbase/2} ${-wheel_separation/2} 0.02" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="right_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit lower="-0.785" upper="0.785" effort="10" velocity="10" />
    </joint>

    <link name="left_front_wheel">
        <inertial>
            <xacro:wheels_inertial_params z_offset="0"/>
        </inertial>
        <visual>
            <xacro:wheel_geometry prefix="left_front" />
        </visual>
        <collision>
           <xacro:wheel_collision_geometry />
        </collision>
    </link>

    <joint name="left_front_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <parent link="left_steering_hinge" />
        <child link="left_front_wheel" />
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="100" />
    </joint>

    <link name="right_front_wheel">
        <inertial>
           <xacro:wheels_inertial_params z_offset="0"/>
        </inertial>
        <visual>
            <xacro:wheel_geometry prefix="right_front" />
        </visual>
        <collision>
            <xacro:wheel_collision_geometry />
        </collision>
    </link>

    <joint name="right_front_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <parent link="right_steering_hinge" />
        <child link="right_front_wheel" />
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="100"/>
    </joint>

    <xacro:include filename="$(find car_description)/urdf/material.xacro" />
    
    <gazebo>  
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find car_description)/config/ackermann_control.yaml</parameters>
            <robot_namespace>/my_ackermann</robot_namespace>
        </plugin>
    </gazebo>

</robot>
