/**:
  ros__parameters:
    # Alap paraméterek (amik a xacro argumentumokból jönnek, és a launch fájlból is felülbírálhatók)
    wheel_radius: 0.05
    wheel_separation: 0.32
    wheelbase: 0.235
    wheel_width: 0.045
    wheel_mass: 0.3
    chassis_mass: 1.0
    steering_hinge_mass: 0.1

    # Odometry parameters (amik eddig az ackermann_control.yaml-ben voltak)
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

    # Velocity and acceleration limits (amik eddig az ackermann_control.yaml-ben voltak)
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.5
    angular.z.min_velocity: -1.5
    angular.z.max_acceleration: 0.8
    angular.z.min_acceleration: -0.8